#debug=true
debug=false

spring.rabbitmq.virtual-host=/
#spring.rabbitmq.host=192.168.0.125
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3s
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.max-interval=10s
spring.rabbitmq.listener.simple.retry.multiplier=2

queue.in.name=SEND_VOUCHER
queue.in.exchange=direct_exchange
queue.in.routingKey=send_voucher
queue.in.duable=true

# Out Queue
queue.out.name=SEND_MESSAGE_RESULT
queue.out.exchange=direct_exchange
queue.out.routingKey=send_message_result
queue.out.duable=true

# DLQ Queue
queue.dlq.name=${queue.in.name}.DLQ
queue.dlq.exchange=${queue.in.exchange}.dlx
queue.dlq.routeKey=${queue.in.routingKey}.dlq
server.port=8085

smsFPT.client-id=client_id_provided_by_fpt
smsFPT.client-secret=client_secret_provided_by_fpt

smsFPT.session-id=noidungngaunhien04172023
smsFPT.uri=https://app.sms.fpt.net
smsFPT.authorization-uri=/oauth2/token
smsFPT.sms-uri=/api/push-brandname-otp
smsFPT.scope=send_brandname_otp send_brandname
smsFPT.grant_type=client_credentials
# FNS FPT
fnsFPT.base-url=https://api-fns.fpt.work
fnsFPT.sending_url=/api/send-message
fnsFPT.app-id=app_id_provided_by_fpt
fnsFPT.secret-key=secret_key_provided_by_fpt 
fnsFPT.lang=vi
fnsFPT.callback_url=https://zaloreport.castis.io/callback_receive
#
spring.main.allow-bean-definition-overriding=true

# ElasticSearch config
#spring.elasticsearch.uris=192.168.0.125:9200
#elastic.url=192.168.0.125:9200
spring.elasticsearch.uris=localhost:9200
elastic.url=localhost:9200

elastic.index.message_callback_sms=ev_message_callback_sms
elastic.index.message_callback_zalo=ev_message_callback_zalo
elastic.index.publish=publish
elastic.index.check_publish=check_publish
# Task Schedule
schedule.fixedDelay=1000
# every hour
schedule.cron=0 0 */1 * * *
#schedule.cron=* */5 * * * *
#schedule lock ever 59 minues
schedule.shedlock=59m
#schedule.shedlock=5m
# 30 second
#schedule.cron=*/30 * * * * *
DATABASE_CONVERTOR_KEY=XaYbCz3579CzXaYb0246813579aBcDeF
# Cipher encrypt/decrypt
cipher.initVector=TotalRandoVector
cipher.key=XaYbCz3579CzXaYb0246813579aBcDeF