#debug=true
debug=false

spring.rabbitmq.virtual-host=/
#spring.rabbitmq.host=192.168.0.125
spring.rabbitmq.host=192.168.0.125
spring.rabbitmq.port=5672
spring.rabbitmq.username=castis
spring.rabbitmq.password=castis
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3s
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.max-interval=10s
spring.rabbitmq.listener.simple.retry.multiplier=2

queue.in.name=SEND_VOUCHER
queue.in.exchange=direct_exchange
queue.in.routingKey=send_voucher
queue.in.duable=true

# Out Queue
queue.out.name=SEND_MESSAGE_RESULT
queue.out.exchange=direct_exchange
queue.out.routingKey=send_message_result
queue.out.duable=true

queue.send.otp.name=SEND_OTP

# DLQ Queue
queue.dlq.name=${queue.in.name}.DLQ
queue.dlq.exchange=${queue.in.exchange}.dlx
queue.dlq.routeKey=${queue.in.routingKey}.dlq
server.port=8085

smsFPT.session-id=noidungngaunhien04172023
smsFPT.uri=https://app.sms.fpt.net
smsFPT.authorization-uri=/oauth2/token
smsFPT.sms-uri-domestic=/api/push-brandname-otp
smsFPT.sms-uri-international=/api/push-brandname-international
smsFPT.scope=send_brandname_otp send_brandname
smsFPT.grant_type=client_credentials
smsFPT.client-id=14506405ab3a095cde6D7c1231f34637481804d5
smsFPT.client-secret=43fbF9Bb2407Ddc78f455b4865594ebc7a9e6A0D0b1D1c96cd0387566819287Fabf3bbaa
# FNS FPT
fnsFPT.base-url=https://api-fns.fpt.work
fnsFPT.sending_url=/api/send-message
fnsFPT.app-id=1683798396
fnsFPT.secret-key=60610dc50928ea26ee4224af5c972c7e 
fnsFPT.lang=vi
fnsFPT.callback_url=https://zaloreport.castis.io/callback_receive
#
spring.main.allow-bean-definition-overriding=true

# ElasticSearch config
#spring.elasticsearch.uris=192.168.0.125:9200
#elastic.url=192.168.0.125:9200
spring.elasticsearch.uris=192.168.0.101:9200
elastic.url=192.168.0.101:9200

elastic.index.message_callback_sms=e_voucher_message_callback_sms
elastic.index.message_callback_zalo=ev_message_callback_zalo
elastic.index.publish=publish
elastic.index.check_publish=check_publish
# Task Schedule
schedule.fixedDelay=1000
# every hour
#schedule.cron=0 0 */1 * * *
schedule.cron=0 0/15 * * * *
#schedule.cron=* */5 * * * *
#schedule lock ever 59 minues
schedule.shedlock=59m
#schedule.shedlock=5m
# 30 second
#schedule.cron=*/30 * * * * *
DATABASE_CONVERTOR_KEY=Database_convertor_key_provided
# Cipher encrypt/decrypt
cipher.initVector=TotalRandoVector
cipher.key=XaYbCz3579CzXaYb0246813579aBcDeF