apiVersion: v1
kind: Service
metadata:
  name: short-link-service-cluster-ip-service
  namespace: production
spec:
  selector:
    app: short-link-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # Replace this with the port your pod is listening on
      name: user-port
    - protocol: TCP
      port: 2000
      targetPort: 2000
      name: internal-app-port
