apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/evoucher-service-fe/
namespace: production
configMapGenerator:
- files:
  - application.properties
  name: evoucher-service-fe-properties
images:
- name: registry.git.altimedia.vn/evoucher/evoucher-service-fe
  newTag: main_9e945ec1
