server.port=19931

### General
# If this config set to true
# Once OTP is requested, its status became USED
system.oneTimeUse=true

### Redis
#redis.host=localhost
redis.host=192.168.0.125
redis.port=6379
redis.isStandAlone=true

### OTP
otp.passwordLength=8
otp.timeToLiveInSec=600
