location:
  log: ./logs/
server:
  port: 8088
contact: 1234-5678

spring:
  application:
    name: E-voucher POS API
  datasource:
    url: ${SECRETS_DB_URL:jdbc:mariadb://192.168.105.88:13306/e_voucher}
    username: ${SECRETS_DB_USERNAME:castis}
    password: ${SECRETS_DB_PASSWORD:castis}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  convertor:
    key: ${DATABASE_CONVERTOR_KEY:XaYbCz3579CzXaYb0246813579aBcDeF}
  # 2024-08-21
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  # end

redis:
  host: 192.168.105.88
  port: 36379
  isStandAlone: false

component:
  service-be:
    url: http://evoucher-service-be-cluster-ip-service/evouchers