apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/pos-api/
namespace: dev
configMapGenerator:
- files:
  - application.yaml
  name: pos-api-properties
images:
- name: registry.git.altimedia.vn/evoucher/pos-api
  newTag: staging_d81855dc
