apiVersion: v1
kind: Service
metadata:
  name: evoucher-service-be-cluster-ip-service
  namespace: production
spec:
  selector:
    app: evoucher-service-be
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083 # Replace this with the port your pod is listening on

