spring.application.name=web_hook
server.servlet.context-path=/
server.port=8089

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url= ${SECRETS_DB_URL:jdbc:mariadb://192.168.105.149:3306/evoucher_latest}
spring.datasource.username= ${SECRETS_DB_USERNAME:evoucher}
spring.datasource.password= ${SECRETS_DB_PASSWORD:Alti@1234}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

log.home=/castis/bin/web-hook/logs

components.service-be.url=${SERVICE_BE_URL:http://192.168.105.149:8083/evouchers}
components.service-fe.url=${SERVICE_FE_URL:http://192.168.105.149:8089}

systems.ur_box.url=https://sandapi.urbox.dev/2.0
systems.ur_box.paths.get-vouchers=/cart/getlist
systems.ur_box.app_secret=${URBOX_APP_SECRET:f8876e0e88b69b1aa1b4411c71931adfq}
systems.ur_box.app_id=${URBOX_APP_ID:500000282}

system.update.voucher.status.cron.ur_box=0 10 1 * * *

# Watane
watane.key-store.path=/castis/bin/web-hook/castis_watane.p12
watane.key-store.password=FzkXp3UnhaMOHFp
watane.key-store.alias=castis_watane_key
watane.key-store.key.password=FzkXp3UnhaMOHFp
watane.ipn.username=watane
watane.ipn.credential=5eRpYXQ2G7ZiOC//e74NhIPXDXFtViyBeK2I96ZhMIM=
watane.ipn.public-key-path=/castis/bin/web-hook/watane_public_key.pem