spring.application.name=web_hook
server.servlet.context-path=/
server.port=8089

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${SECRETS_DB_URL:jdbc:mariadb://192.168.0.125:3306/e_voucher}
spring.datasource.username= ${SECRETS_DB_USERNAME:castis}
spring.datasource.password= ${SECRETS_DB_PASSWORD:castis}
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

log.home=/Users/daont/CastisDocuments/e-voucher/log/

components.service-be.url=${SERVICE_BE_URL:http://192.168.0.125:8083/evouchers}
components.service-fe.url=${SERVICE_FE_URL:http://192.168.0.125:19932}

systems.ur_box.url=https://sandapi.urbox.dev/2.0
systems.ur_box.paths.get-vouchers=/cart/getlist
systems.ur_box.app_secret=${URBOX_APP_SECRET:f8876e0e88b69b1aa1b4411c71931adf}
systems.ur_box.app_id=${URBOX_APP_ID:500000282}

system.update.voucher.status.cron.ur_box=1 0 * * * *