apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXQuYWx0aW1lZGlhLnZuIjp7InVzZXJuYW1lIjoicGlwZWxpbmUtYXQiLCJwYXNzd29yZCI6IkFsdGlAMTIzNCIsImVtYWlsIjoicGlwZWxpbmUtYXRAZXhhbXBsZS5jb20iLCJhdXRoIjoiY0dsd1pXeHBibVV0WVhRNlFXeDBhVUF4TWpNMCJ9fX0=
kind: Secret
metadata:
  name: regcred
  namespace: dev
type: kubernetes.io/dockerconfigjson
