spring.application.name=partner_service
server.servlet.context-path=/
server.port=8090

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${SECRETS_DB_URL:jdbc:mariadb://192.168.23.104:13306/e_voucher}
spring.datasource.username= ${SECRETS_DB_USERNAME:castis}
spring.datasource.password= ${SECRETS_DB_PASSWORD:castis}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

log.home=./logs/

partner.vnpt.default.uri=http://naptien.thanhtoan247.net.vn:8082/CDV_Partner_Services_V1.0/services/Interfaces
partner.vnpt.partner.name=aquaretail
partner.vnpt.private-key=MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAKvvqk9aYgoeYg+lCopklZJXRco5L+45cM1j16Y65WJWMHi+CNk4IM+LKVGAnpjJEd7cLLkQGXw5+8pSrlbUa8w47Ao0qH5QzmKLbWI/JEagC3nZwij6I8JWCQ3u27V2Pmknp0Z5LkvMvn5ybcU9oC8yVxTCGWUQsDeQNdGxX28FAgMBAAECgYB10ZSmLexSvME7sT/I1+Y60r0LNybmGsx2oj1LNr6rJR6wDqDnoPOy5MyaggWr8tThH4UyB5s/KkilOwUmkQeQVP5rFnvliVnyS5B2JvM5lMKyCPwhIq6hEu0C55ASP7m17fuc8tnFupj2e1F22nGMlfSPBrvxWQCBSsasYZEsHQJBAPutsSzur85ZgXK/02EZQEKKJS0TpCIqy1LpXLMT90WupH5gXX8o4hCtwiMxYIxvn85aO0vHIwn6gB4Pdds/E7sCQQCu43LO2lPS5ei+UnG5d5A/PAJYYg2HgEbtytezzXqG45D4u2SMMVwkieXBca4KOOHveGlrOQh5oY1zByRxsXw/AkAGnOe84ICqEVv/Yd7x/DHeDbcwWgXECA/Tm+Idqnai1BXqZCnQv4hBG++v8QoyZnRyfZh1Q0Q+bOCU6Z8VJbElAkAWlBzFYeCCkNYchC5UgIAp+chfusD+ZmxB1PdGKlgQRB76Tc8sXk8EFJ2J/PA4N6HLteL+Sc2zTk0htaFZ4E0nAkAL4usrAOihzlUKLCKoHmdbrCG9LCfZKpiiOJIEzs/Gdk+zlV93enaVjVK+WEJ0GUwL6fe6sOcEnBSGO7WuGe5n
partner.vnpt.card.key=EB16DCB7C983B0DB463AD1D3E4D49401


logging.level.com.com.evoucher.partner.service=INFO
logging.level.org.springframework.ws=INFO

springfox.documentation.enabled=false
springfox.documentation.open-api.enabled=false

spring.convertor.key=${DATABASE_CONVERTOR_KEY:XaYbCz3579CzXaYb0246813579aBcDeF}
#2024-08-26
spring.jackson.time-zone=Asia/Ho_Chi_Minh
#end

# 2025-03-25
evoucher.service-be.url=http://evoucher-service-be-cluster-ip-service
scheduler.voucher.vnpt.pending.cron=0 */5 * * * *
scheduler.voucher.vnpt.retry.max=5
rest.template.timeout.sec=120 

# 2025-04-17 xpay integration
xpay.api.url=https://partner2.ypay.vn:8686/PartnerAPI
xpay.acc.id=9008
xpay.username=aqua
xpay.secret.key=65cb59645b852c2394ba3ff8b295e83c
xpay.decrypt.key=313337e769124836142f8d9c016114a2
xpay.public.key=keys/xpay_public_key.pem
aqua.xpay.private.key=keys/aqua_xpay_private_key.pem