apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/partner-service/
namespace: production
configMapGenerator:
- files:
  - application.properties
  name: partner-service-properties
images:
- name: registry.git.altimedia.vn/evoucher/partner-service
  newTag: main_553bd033
