#spring.profiles.active=dev
spring.application.name=evoucher-api
server.port=1993
spring.mvc.format.date-time=yyyy-MM-dd' 'HH:mm:ss

spring.datasource.url=jdbc:mariadb://192.168.105.149:3306/evoucher_latest
# Staging
#spring.datasource.url=jdbc:mariadb://192.168.0.183:13306/e_voucher
spring.datasource.username=evoucher
spring.datasource.password=Alti@1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
redis.host=192.168.105.149
redis.port=6379
redis.isStandAlone=true
redis.lock.choice=CHOOSE_CHOICE_

spring.rabbitmq.host=192.168.105.149
spring.rabbitmq.port=5672
spring.rabbitmq.username=castis
spring.rabbitmq.password=castis

rabbitmq.queue.USED_VOUCHER=USED_VOUCHER_
rabbitmq.routingKey.USED_VOUCHER=used_voucher_
rabbitmq.exchange.USED_VOUCHER=direct_exchange

rabbitmq.queue.TRANSFER_VOUCHER=REQUEST_HANDOVER_
rabbitmq.routingKey.TRANSFER_VOUCHER=transfer_voucher_
rabbitmq.exchange.TRANSFER_VOUCHER=direct_exchange

rabbitmq.queue.RECEIPT_VOUCHER=RECEIVED_VOUCHER_
rabbitmq.routingKey.RECEIPT_VOUCHER=receive_voucher_
rabbitmq.exchange.RECEIPT_VOUCHER=direct_exchange

encryption.key=XaYbCz3579CzXaYb0246813579aBcDeF

evoucher.otpservice=http://192.168.105.149:19931
evoucher.service-fe.url=http://192.168.105.149:19932
evoucher.service-be.url=http://192.168.105.149:8083
evoucher.publish-service.url=http://192.168.105.149:8081/publish-service

# Config Google Translate API
evoucher.google.translate.url=https://translation.googleapis.com/language/translate/v2
evoucher.google.translate.key=YOUR_GOOGLE_API_KEY

#elastic.url=192.168.23.104:19200
elastic.url=192.168.0.101:9200
elastic.voucher.indexName=voucher
elastic.publish.indexName=publish
elastic.store.indexName=store
elastic.payment.history.indexName=payment_history
elastic.transfer.history.indexName=transfer_history

otp.expire.time=10
otp.expire.timeCancelPayment=7
otp.expire.voucher.time=30

urlyBud=http://192.168.105.149:2000
tokenBud=c4e0f406-4bb1-4a74-8e46-83fafdda3776

spring.jackson.time-zone=Asia/Ho_Chi_Minh

rest.template.timeout.sec=180