apiVersion: v1
kind: PersistentVolume
metadata:
  name: jmetter-pv
  labels:
    app: jmetter
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: /data/jmetter
    server: 192.168.23.104
