apiVersion: v1
kind: Service
metadata:
  name: evoucher-api-cluster-ip-service
  namespace: production
spec:
  selector:
    app: evoucher-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1992 # Replace this with the port your pod is listening on

