spring.application.name=partner_service
server.servlet.context-path=/
server.port=8090

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=${SECRETS_DB_URL:jdbc:mariadb://192.168.0.125:3306/e_voucher}
spring.datasource.username= ${SECRETS_DB_USERNAME:castis}
spring.datasource.password= ${SECRETS_DB_PASSWORD:castis}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jackson.time-zone=Asia/Ho_Chi_Minh

log.home=/castis/bin/partner-service/logs

partner.vnpt.default.uri=http://itopup-test.megapay.net.vn:8082/CDV_Partner_Services/services/Interfaces
partner.vnpt.partner.name=partnerTest
partner.vnpt.private-key=MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKLYA/kxjcWQWaAsMT3XTuOIO0lSWwEwVpm6NUQIaEsklKtc2w481K/8+LVykyrrPs3sQyEdPPOTuzR6oJ/O4S1UyraYTj3n6vAuhqyu9p4A3DUJTIJjX3oh8HTDC36tPiJkKXLEQuxtq8BAym9Qn3/5iMoW/cF/Ib7/17r/I2EbAgMBAAECgYEAmhUhdVnRFp3mYCtQkH44tAyEZHVbjL1rQ9wwaGY4INnFHnwm/crLSJZp0m5OGC8tZvVl82BR+vvPB/H8KBo9bv4nLKC5GkuI4kUvwptCvRADz+lXmzTQZUej7/yDV2cTvhTC2k586Qx2wCyxi0up7M1uu3kdjbqZyx4Qpa4cVWkCQQDfyueALxM759PLF7BA6J0mf4sKAYU13LYAmXRpcYh8RDsfQWbgcNv8eHFHzlZ3l66dHnP0f4+A4y6nrelkg8ilAkEAukeZ2ykGZeaHAF/2ymH4u88WpBz38xnj8meA8/P71kwnrUQYSSpRGioQBb8Z+mLj65yLlJDmuKF+3rBpIECWvwJBAIZqNX+9Rp0tkf0i3j8uN+1+n8FDxoHibgKQKOaIRYT16ljMjIDz6H2MzeVmHnM4TK2cM+M/lq7ARS57e3pe2O0CQGSwyWCmx1eTiYvRU5RH6uyR3xossnZMm2NvQUwcqRdIKPZGZZ4+6oHrFKgWiVNH2w2DnAtdW+mXGf4De3+8if8CQBSN7PTZhc65J3pdfGeQ563U/ALfZAVU8e9Jv762WT/AzzYrrHKAIvKOR9LZzVyddLB7GPpvgBohheycUHCalNU=
partner.vnpt.card.key=123456abc


logging.level.com.com.evoucher.partner.service=INFO
logging.level.org.springframework.ws=INFO

springfox.documentation.enabled=true
springfox.documentation.open-api.enabled=true