apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../../base/admin-api
configMapGenerator:
- files:
  - application.yaml
  - castis_watane.p12
  name: admin-api-properties
images:
- name: registry.git.altimedia.vn/evoucher/admin-api
  newTag: staging_04fb1ea5
