server.port=9999
sms.callback_receive.user=sms_fpt
sms.callback_receive.password=EVSmsReceiver#23

# ElasticSearch config
#elastic.url=localhost:9200
elastic.url=192.168.23.104:19200
#elastic.index=ev_message
elastic.index.pa=ev_message
elastic.index.callback_receive_sms=e_voucher_message_callback_sms
