apiVersion: v1
kind: Service
metadata:
  name: otp-service-cluster-ip-service
  namespace: production
spec:
  selector:
    app: otp-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 19931 # Replace this with the port your pod is listening on

