apiVersion: v1
kind: Service
metadata:
  name: admin-cms-ui-cluster-ip-service
  namespace: production
spec:
  selector:
    app: admin-cms-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Replace this with the port your pod is listening on
