apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/publish-service/
namespace: dev
configMapGenerator:
- files:
  - application.yaml
  - urboxStore.p12
  - castis_watane.p12
  name: publish-service-properties
images:
- name: registry.git.altimedia.vn/evoucher/publish-service
  newTag: staging_324da0d9
