apiVersion: v1
kind: Service
metadata:
  name: external-service-api-cluster-ip-service
  namespace: production
spec:
  selector:
    app: external-service-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084 # Replace this with the port your pod is listening on