apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-api
  template:
    metadata:
      labels:
        app: admin-api
    spec:
      containers:
        - name: admin-api
          image: registry.git.altimedia.vn/evoucher/admin-api:main
          ports:
            - containerPort: 8080 # Replace this with the port the application listens on
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: admin-api-properties
      imagePullSecrets:
        - name: regcred
