apiVersion: v1
kind: Service
metadata:
  name: image-server-cluster-ip-service
  namespace: production
spec:
  selector:
    app: image-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000 # Replace this with the port your pod is listening on

