apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-server-cluster-ip-service.yaml
  - image-server-deployment.yaml
  - persistent-volume-claim-image-server.yaml
  - persistent-volume-image-server.yaml