apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-server-pv
  labels:
    app: image-server
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: /data/image_server
    server: 192.168.23.104
