apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/publish-service/
namespace: production
configMapGenerator:
- files:
  - application.yaml
  - castis_urbox.p12
  - castis_watane.p12
  name: publish-service-properties
images:
- name: registry.git.altimedia.vn/evoucher/publish-service
  newTag: main_7470e7ff
