spring.application.name=Evoucher-Service-FE
server.port=19932
#logging.config=file:/castis/bin/evoucher-service-fe/logback.xml
system.log.prettify=true

system.decrypt.vector=TotalRandoVector
system.decrypt.key=XaYbCz3579CzXaYb0246813579aBcDeF

push.zalo.templateId=TEMPLATE_ZALO_113
push.brandName=AQUA_VOUCHER
message.path.template.en=/Users/nguyentai/workspace/git/evoucher-service-fe/src/main/resources/message_template_en.json
message.transfer.path.template.en=/Users/nguyentai/workspace/git/evoucher-service-fe/src/main/resources/transfer_message_template_en.json

castis.component.publish-service.url=http://192.168.105.149:8081/publish-service

#################################
### Rabbit MQ ###################
#################################
spring.rabbitmq.host=192.168.105.149
spring.rabbitmq.port=5672
spring.rabbitmq.username=castis
spring.rabbitmq.password=castis

#spring.rabbitmq.host=localhost
#spring.rabbitmq.port=5672
#spring.rabbitmq.username=guest
#spring.rabbitmq.password=guest

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000ms
spring.rabbitmq.listener.simple.retry.multiplier=2.0

### Read messages from Publish service (Save publish & vouchers to ES and create messages)
rabbitmq.in.queue.publish=PUBLISH_VOUCHER
rabbitmq.in.exchange.publish=direct_exchange
rabbitmq.in.routingKey.publish=publish_voucher
rabbitmq.in.durable.publish=true

### Write messages to Push Agent (Create message for Push Agent)
rabbitmq.out.exchange.publish=direct_exchange
rabbitmq.out.routingKey.publish=send_voucher
rabbitmq.out.durable.publish=true
rabbitmq.out.queue.publish=SEND_VOUCHER

### Write messages to Publish service (Update message creation status)
rabbitmq.out.exchange.result=direct_exchange
rabbitmq.out.routingKey.result=generate_result
rabbitmq.out.durable.result=true
rabbitmq.out.queue.result=GENERATE_RESULT

### Write messages to Publish service (Update job result status | expire job + restore job)
rabbitmq.out.exchange.jobResult=direct_exchange
rabbitmq.out.routingKey.jobResult=update_voucher
rabbitmq.out.durable.jobResult=true
rabbitmq.out.queue.jobResult=UPDATE_VOUCHER

### Read messages from Publish service (Save store info from Backend)
rabbitmq.in.exchange.store=direct_exchange
rabbitmq.in.routingKey.store=update_store
rabbitmq.in.durable.store=true
rabbitmq.in.queue.store=UPDATE_STORE

#################################
### Elastic search ##############
#################################
#elastic.host=localhost
#elastic.port=9200
elastic.host=192.168.0.101
elastic.port=9200

elastic.basicAuth=false
elastic.username=castis
elastic.password=castis

elastic.voucher.indexName=voucher
elastic.publish.indexName=publish
elastic.store.indexName=store
elastic.transferHistory.indexName=transfer_history

#################################
### Quartz ######################
#################################
# Quartz Scheduler Configuration
#spring.quartz.job-store-type=memory
# Job scheduling
# Every 2 days
#quartz.expireVoucher.cron=0 0 0 1/2 * ? *
#quartz.expireVoucher.cron=0 * * ? * *
# every minute

### Expire job
quartz.expireVoucher.enabled=false
quartz.expireVoucher.cron=0 0 0 1/2 * ? *
quartz.expireVoucher.retryCount=2
quartz.expireVoucher.voucherDurationInDays=2

### Restore job
quartz.restoreVoucher.enabled=false
quartz.restoreVoucher.cron=0 0 0 1/2 * ? *
quartz.restoreVoucher.retryCount=2
quartz.restoreVoucher.confirmWaitDurationInDays=2

### Write messages to SMS OTP
rabbitmq.out.exchange.otp=direct_exchange
rabbitmq.out.routingKey.otp=send_otp
rabbitmq.out.durable.otp=true
rabbitmq.out.queue.otp=SEND_OTP


### Disable voucher
rabbitmq.in.exchange.disable=direct_exchange
rabbitmq.in.routingKey.disable=disable_voucher
rabbitmq.in.durable.disable=true
rabbitmq.in.queue.disable=DISABLE_VOUCHER

### Disable voucher result
rabbitmq.out.exchange.disableResult=direct_exchange
rabbitmq.out.routingKey.disableResult=disable_voucher_result
rabbitmq.out.durable.disableResult=true
rabbitmq.out.queue.disableResult=DISABLE_VOUCHER_RESULT

### Resend voucher
rabbitmq.in.exchange.resend=direct_exchange
rabbitmq.in.routingKey.resend=resend_voucher
rabbitmq.in.durable.resend=true
rabbitmq.in.queue.resend=RESEND_VOUCHER


### Activate voucher
rabbitmq.out.exchange.activate=direct_exchange
rabbitmq.out.routingKey.activate=activate_voucher
rabbitmq.out.durable.activate=true
rabbitmq.out.queue.activate=ACTIVATE_VOUCHE

spring.quartz.job-store-type=jdbc
# Always create the Quartz database on startup
spring.quartz.jdbc.initialize-schema=always
spring.datasource.jdbc-url=jdbc:h2:mem:spring-quartz;DB_CLOSE_ON_EXIT=FALSE;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jackson.time-zone=Asia/Ho_Chi_Minh
message.otp.template=[aQua VN] AQUA RETAIL gui ban mot mon qua lua chon. Vui long truy cap vao link de nhan qua: https://ev.aqua.gift. Ma OTP cua ban la %s
evoucher.service-be.url=http://192.168.105.149:8083

# send mail
spring.mail.host=aquaretail.hanbiro.net
spring.mail.port=465
spring.mail.username=no_reply@aquaretail.net
spring.mail.password=aqua1234!
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable = true
spring.mail.properties.mail.smtp.ssl.required = true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false

email.subject=Moi ban trai nghiem mua sam thu vi cung aQua voucher
email.template=emailTemplate
customer.name.default.en=customer
customer.name.default.vi=hang

feign.client.config.default.connectTimeout=120000
feign.client.config.default.readTimeout=120000

rest-template.connectTime=120000
rest-template.readTimeout=120000


