apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/frontend-ui/
namespace: dev
images:
- name: registry.git.altimedia.vn/evoucher/frontend-ui
  newTag: staging_973b9ea1
