apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-cluster-ip-service.yaml
  - prometheus-configmap.yaml
  - prometheus-deployment.yaml
  - prometheus-role.yaml
  - prometheus-node-exporter.yaml