apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/sms-callback-receive/
namespace: dev
configMapGenerator:
- files:
  - application.properties
  name: sms-callback-receive-properties
images:
- name: registry.git.altimedia.vn/evoucher/sms-callback-receive
  newTag: staging_01f61587
- name: registry.git.altimedia.vn/evoucher/sms_callback_receive
  newTag: staging_01f61587
