server.port=19931

### General
# If this config set to true
# Once OTP is requested, its status became USED
system.oneTimeUse=true

### Redis
#redis.host=localhost
redis.host=192.168.105.88
redis.port=36379

### OTP
otp.passwordLength=8
otp.timeToLiveInSec=600

#2024-08-21
spring.jackson.time-zone=Asia/Ho_Chi_Minh
#end