spring.profiles.active=production
spring.application.name=evoucher-api
server.port=1992
spring.mvc.format.date-time=yyyy-MM-dd' 'HH:mm:ss

spring.rabbitmq.host=192.168.23.104
spring.rabbitmq.port=35672
spring.rabbitmq.username=castis
spring.rabbitmq.password=castis

rabbitmq.queue.USED_VOUCHER=USED_VOUCHER
rabbitmq.routingKey.USED_VOUCHER=used_voucher
rabbitmq.exchange.USED_VOUCHER=direct_exchange

rabbitmq.queue.TRANSFER_VOUCHER=REQUEST_HANDOVER
rabbitmq.routingKey.TRANSFER_VOUCHER=transfer_voucher
rabbitmq.exchange.TRANSFER_VOUCHER=direct_exchange

rabbitmq.queue.RECEIPT_VOUCHER=RECEIVED_VOUCHER
rabbitmq.routingKey.RECEIPT_VOUCHER=receive_voucher
rabbitmq.exchange.RECEIPT_VOUCHER=direct_exchange

encryption.key=XaYbCz3579CzXaYb0246813579aBcDeF

evoucher.otpservice=http://otp-service-cluster-ip-service:80
elastic.url=192.168.23.104:19200
elastic.voucher.indexName=voucher
elastic.publish.indexName=publish
elastic.store.indexName=store
elastic.payment.history.indexName=payment_history
elastic.transfer.history.indexName=transfer_history

otp.expire.time=10
otp.expire.timeCancelPayment=7

#new config 2024-01-12
evoucher.service-fe.url=http://evoucher-service-fe-cluster-ip-service
evoucher.service-be.url=http://evoucher-service-be-cluster-ip-service

#remove evoucher viewer 2024-01-12
urlyBud=http://short-link-service-cluster-ip-service:2000
tokenBud=fc51b9c5-46a6-4909-947f-66891403f7f7
#2024-08-09
otp.expire.voucher.time=43200
#end
#2024-06-18
spring.datasource.url=jdbc:mariadb://192.168.23.104:13306/e_voucher
spring.datasource.username=castis
spring.datasource.password=castis
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

redis.host=192.168.23.104
redis.port=36379
redis.isStandAlone=false
redis.lock.choice=CHOOSE_CHOICE_

#2024-08-26
spring.jackson.time-zone=Asia/Ho_Chi_Minh
#end
#2024-10-04
evoucher.publish-service.url=http://publish-service-cluster-ip-service/publish-service
#end
#2024-10-08
rest.template.timeout.sec=120
#end

# 2025-03-25
rest.template.timeout.sec=120
#Config Google Translate API
evoucher.google.translate.url=https://translation.googleapis.com/language/translate/v2
evoucher.google.translate.key=AIzaSyB-D-moiEgbo63u4TBbfsS-SMNewxZ3Hic