apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/evoucher-api/
namespace: production
configMapGenerator:
- files:
  - application.properties
  name: evoucher-api-properties
images:
- name: registry.git.altimedia.vn/evoucher/evoucher-api
  newTag: main_321ccaa9
