spring.application.name=web_hook
server.servlet.context-path=/
server.port=8089

spring.datasource.driver-class-name= org.mariadb.jdbc.Driver
spring.datasource.url= ${SECRETS_DB_URL:jdbc:mariadb://192.168.23.104:13306/e_voucher}
spring.datasource.username= ${SECRETS_DB_USERNAME:castis}
spring.datasource.password= ${SECRETS_DB_PASSWORD:castis}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true

log.home=/app/log/

components.service-be.url=${SERVICE_BE_URL:http://evoucher-service-be-cluster-ip-service/evouchers}
components.service-fe.url=${SERVICE_FE_URL:http://evoucher-service-fe-cluster-ip-service}

systems.ur_box.url=https://api.urbox.vn/2.0
systems.ur_box.paths.get-vouchers=/cart/getlist
systems.ur_box.app_secret=${URBOX_APP_SECRET:99c0a4d73dc4792cfee496f938d121b7}
systems.ur_box.app_id=${URBOX_APP_ID:1340}

system.update.voucher.status.cron.ur_box=0 0 2 * * *

# WATANE Live Production 
watane.key-store.path=/app/config/castis_watane.p12
watane.key-store.password=FzkXp3UnhaMOHFp
watane.key-store.alias=castis_watane_key
watane.key-store.key.password=FzkXp3UnhaMOHFp
watane.ipn.username=watane
watane.ipn.credential=vyHVqjtmt4eQ/fGU59DwVKDjCI/A7fKAKuwRNwSSzsI=
watane.ipn.public-key-path=/app/config/payoox_public.pem