apiVersion: v1
kind: Service
metadata:
  name: publish-service-cluster-ip-service
  namespace: production
spec:
  selector:
    app: publish-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081 # Replace this with the port your pod is listening on

