apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ingress-evoucher.yaml
 - ingress-short-link.yaml
 - ingress-monitoring.yaml
namespace: production
secretGenerator:
  - name: b2b.aquavoucher.com
    files:
      - tls.crt=ssl-cert/b2b.aquavoucher.com/cert.pem
      - tls.key=ssl-cert/b2b.aquavoucher.com/unencrypted-key.pem
  - name: aqua.gift
    files:
      - tls.crt=ssl-cert/aqua.gift/cert.pem
      - tls.key=ssl-cert/aqua.gift/unencrypted-key.pem