apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../../base/admin-cms-ui
images:
- name: registry.git.altimedia.vn/evoucher/cms-ui
  newTag: staging_eb994421
