server:
  servlet:
    context-path: /
  port: 8083

spring:
  application:
    name: eVoucher-service-BE
  datasource:
    url: ${SECRETS_DB_URL:jdbc:mariadb://192.168.105.88:13306/e_voucher}
    username: ${SECRETS_DB_USERNAME:castis}
    password: ${SECRETS_DB_PASSWORD:castis}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  convertor:
    key: ${DATABASE_CONVERTOR_KEY:XaYbCz3579CzXaYb0246813579aBcDeF}
  jackson:
    time-zone=: Asia/Ho_Chi_Minh
  rabbitmq:
    host: ${RABBIT_MQ_HOST:192.168.105.88}
    port: ${RABBIT_MQ_PORT:35672}
    username: ${RABBIT_MQ_USER_NAME:castis}
    password: ${RABBIT_MQ_PASSWORD:castis}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 100
short-link:
  url:
    request: ${SHORT_LINK_URL_REQUEST:http://short-link-service-cluster-ip-service:2000}
    token: ${SHORT_LINK_URL_TOKEN:b24cb8b5-1fa1-4d6d-862a-8e9f93bb9dc6}
    redirect: ${SHORT_LINK_URL_REDIRECT:https://ub-urly.altimedia.vn}
    target: ${APPLICATION_URL:https://userui.aqua.altimedia.vn/voucher}
    #2024-05-05
    activate: ${ACTIVATION_URL:https://userui.aqua.altimedia.vn/activate}
    #end

queues:
  exchange: ${RABBIT_EXCHANGE:direct_exchange}
  used_voucher:
    queue: ${QUEUE_USED_VOUCHER:USED_VOUCHER}
    routingKey: ${QUEUE_USED_VOUCHER_KEY:used_voucher}
  receive_voucher:
    queue: ${QUEUE_RECEIVE_VOUCHER:RECEIVED_VOUCHER}
    routingKey: ${QUEUE_RECEIVE_VOUCHER_KEY:receive_voucher}
  update_voucher:
    queue: ${QUEUE_UPDATE_VOUCHER:UPDATE_VOUCHER}
    routingKey: ${QUEUE_UPDATE_VOUCHER_KEY:update_voucher}
  #2024-02-29
  disable_voucher:
    queue: ${QUEUE_DISABLE_VOUCHER:DISABLE_VOUCHER}
    routingKey: ${QUEUE_DISABLE_VOUCHER_KEY:disable_voucher}
  disable_voucher_result:
    queue: ${QUEUE_DISABLE_VOUCHER_result:DISABLE_VOUCHER_RESULT}
    routingKey: ${QUEUE_DISABLE_VOUCHER_RESULT_KEY:disable_voucher_result}
  #end
  #2024-05-05
  activate_voucher:
    queue: ${QUEUE_ACTIVATE_VOUCHER:ACTIVATE_VOUCHER}
    routingKey: ${QUEUE_ACTIVATE_VOUCHER_KEY:activate_voucher}
  #end
#2024-02-29
servers:
  publishServer: ${PUBLISH_SERVER_URL:http://publish-service-cluster-ip-service/publish-service}
#2024-06-07
redis:
  host: 192.168.105.88
  port: 36379
  isStandAlone: false
  key:
    buy-choice:
      prefix: CHOOSE_CHOICE_
#2024-07-26
system:
  partner-service:
    url: http://partner-service-cluster-ip-service/
#end
#2024-10-08
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 120000
# 2025-03-25
  rest-template:
    connectTime: 120000
    readTimeout: 120000