apiVersion: v1
kind: Service
metadata:
  name: partner-service-cluster-ip-service
  namespace: production
spec:
  selector:
    app: partner-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090 # Replace this with the port your pod is listening on