apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../../base/image-server
patches:
- path: pv-patch.yaml
  target:
    kind: PersistentVolume
    name: image-server-pv
    version: v1
- path: pvc-patch.yaml
  target:
    kind: PersistentVolumeClaim
    name: image-server-pvc
    version: v1
images:
- name: registry.git.altimedia.vn/evoucher/evoucher-image-server
  newTag: staging_f36dc05c
