apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/vnpt-epay-dummy
namespace: production
#Generate ConfigMap for app config
configMapGenerator:
  - name: vnpt-epay-dummy-properties
    files:
    - application.yaml