apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/push-agent/
namespace: production
configMapGenerator:
- files:
  - application.properties
  name: push-agent-properties
images:
- name: registry.git.altimedia.vn/evoucher/push-agent
  newTag: main_5993f893
