apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/web-hook/
namespace: dev
configMapGenerator:
- files:
  - application.properties
  - castis_watane.p12
  - watane_public_key.pem
  name: web-hook-properties
images:
- name: registry.git.altimedia.vn/evoucher/web-hook
  newTag: staging_264c7d58
