apiVersion: v1
kind: Service
metadata:
  name: pos-api-cluster-ip-service
  namespace: production
spec:
  selector:
    app: pos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088 # Replace this with the port your pod is listening on

