apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base/shortlink-service/
namespace: production
images:
- name: registry.git.altimedia.vn/evoucher/shortlink-service
  newTag: master_5be565f8